### ISSUE TITLE
서버에서 다시 보지 않기 처리 여부

### ISSUE THREAD

**Issue by kairos03** [GamePlatform/Campaign-wiki#2]
다시 보지 않기 값을 앱 내에 말고 서버에 저장하여 처리

**Comment by ReportSubmit** [comment]
정정.. 앱내에 안보기한 광고 ID를 저장해두고 다음 요청시 제외목록파라미터에 넣어 보내기

**Comment by kairos03** [comment]
GamePlatform/Campaign-SDK#17
