### ISSUE TITLE
광고 요청(GET, /api/campaign/~) v0.0.2

### ISSUE THREAD

**Issue by ReportSubmit** [GamePlatform/Campaign-wiki#3]

**Comment by kairos03** [comment]
https://github.com/GamePlatform/Campaign-wiki/wiki

**Comment by kairos03** [comment]
/api/campaign/locations/{locaitonID(String)}?app_id={appID(String)}&device_id={deviceID(String)}&except_campaign={campaginID_1(String)}&except_campaign={campaginID_2(String)}&except_campaign={campaginID_3(String)}

너무 길어지는거 같은데 차라리 POST body에 JSON으로 넘기는게 낫지 않을까요?

**Comment by ReportSubmit** [comment]
/api/campaign/locations/{locaitonID(String)}?aid={appID(String)}&did={deviceID(String)}&ec={campaginID_1(String)}&ec={campaginID_2(String)}&ec={campaginID_3(String)}

일단 위처럼 줄였어요

POST 써버리면 REST에서 벗어나버려요 저희가 서버에 어떤 값을 생성하려는게 아니라서 GET을 써야되요

아래는 구글에 '컴퓨터' 검색해봣을 때 전체 길이에요
https://www.google.co.kr/webhp?hl=ko&sa=X&ved=0ahUKEwjTpvCGyZbUAhXGWLwKHVzHDy8QPAgD#newwindow=1&hl=ko&q=%EC%BB%B4%ED%93%A8%ED%84%B0

저희 URL도 길이가 최소 길이는

/api/campaign/locations/{locaitonID(String)}?aid={appID(String)}&did={deviceID(String)}

이정도이고

최대 길이는 광고 다시 보지 않기를 누른 개수 만큼 붙을 것 같은데 

get에서 길이에 대한 제한은 2000자 까지 가능하니 괜찮을 것 같아요

http://uiandwe.tistory.com/1133 <-  get방식 길이 테스트 

@vi01et03

**Comment by kairos03** [comment]
네 알겠습니다 
그럼 그렇게 진행해 주세요
@ReportSubmit 

이거 참고해서 광고 요청 부분 처리 해주세요
@GooSeng
